---
title: "Homework 5"
author: "Anushka Canfield"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question One: 
```
Use variable n_dims to do the following:
```
```{r}
## Create a vector of consecutive integers from 1 to n_dims2
n_dims <- 3:10

## Use the sample function to randomly reshuffle these values.
my_vec <- 1:(n_dims)^2
sample(my_vec)

## create a square matrix with these elements.
my_mat <- matrix(data=my_vec, ncol=3)

##print out the matrix.
print(my_mat)

## find a function in r to transpose the matrix.
transpose_mat <- t(my_mat)

##print it out again and note how it has changed.
print(transpose_mat)

##calculate the sum and the mean of the elements in the first row and then the last row.
get_row_1 <- transpose_mat[1,]
sum_row_1 <- c(get_row_1[1] + get_row_1[2] + get_row_1[3])
mean_list <- c(get_row_1[1], get_row_1[2], get_row_1[3])
mean_row_1 <- mean(mean_list)
sum_row_1
mean_row_1

##read about the eigen() function and use it on your matrix
get_row_last <-transpose_mat[3,]
sum_row_last <- get_row_last[1] + get_row_last[2] + get_row_last[3]
sum_row_last

eigen_test <- eigen(my_mat)
eigen_test

## look carefully at the elements of $values and $vectors in the output. What kind of numbers are these?
typeof(eigen_test$values)
typeof(eigen_test$vectors)

```

# Question Two:
```
Create a list with the following named elements:
```

```{r}
## my_matrix, which is a 4 x 4 matrix filled with random uniform values
matrix_filler <- runif(1:16)
my_matrix <- matrix(matrix_filler,nrow=4,ncol=4)
my_matrix

## my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
my_logical <- 1:100
random_numbers <- sample(my_logical)
T_F_vector <- random_numbers > 25
T_F_vector

## my_letters, which is a 26-element vector of all the lower-case letters in random order.
my_letters <- paste(letters[1:26])
random_letters <- sample(my_letters)
random_letters

```
```
Combine named elements
```

```{r}
## create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.
new_list <- c(my_matrix[2,2], T_F_vector[2], random_letters[2])

## use the typeof() function to confirm the underlying data types of each component in this list
typeof(my_matrix[2,2])
typeof(T_F_vector[2])
typeof(random_letters[2])

##combine the underlying elements from the new list into a single atomic vector with the c() function. What is the data type of this vector?
typeof(new_list)

```

# Question Three:
```
Create a data frame with the two variables (= columns) and 26 cases (= rows) below:
```

```{r}

dFrame <- data.frame(x=my_unis, y=rand_up_letters)
dFrame

## call the first variable my_unis and fill it with 26 random uniform values from 0 to 10

my_unis <- runif(26,1,10)
my_unis

##call the second variable my_letters and fill it with 26 capital letters in random order.
letters <- paste(letters[1:26])
up_letters <- toupper(letters)
rand_up_letters <- sample(up_letters,26)

## for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
dFrame[runif(4,1,26),1] <- NA
dFrame

## for the first variable, write a single line of R code to identify which rows have the missing values.
na_rows <- dFrame[is.na(dFrame),]
na_rows

##re-order the entire data frame to arrange the second variable in alphabetical order

alphabetic <- dFrame[sort(,dFrame$y)]

## calculate the column mean for the first variable.
mean_list <- unlist(dFrame)
mean_x <- mean(mean_list)
mean_x


```





