---
title: "Homework 10"
author: "Anushka Canfield"
date: "2024-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##############################
# FUNCTION: Calculate Zeros in Given Vector
# input: Vector List
# output: Number of Zeros
# -------------------
calc_zeros <- function(vector_list){
  counter <- 0
  for (i in vector_list) {
    if (i == 0)
    counter <- counter + 1
  }
  return(counter)
}
##############################

my_list <- c(10,0,0,0,0,5,7,0)
my_list

calc_zeros(vector_list = my_list)

calc_zeros_subsetting <- function(vector_list) { sum(vector_list == 0) }
calc_zeros_subsetting(my_list)

```

```{r}

##############################
# FUNCTION: Create a Matrix from Inputs
# input: Number of rows and columns
# output: the matrix
# -------------------
make_a_matrix <- function(vector, nRow, nCol){
  matrix <- matrix(vector, nRow, nCol)
  return(matrix)
}
##############################

my_list <- sample(100,10)
make_a_matrix(vector = my_list, nRow = 5, nCol = 6)

```


```{r}

##############################
# FUNCTION: Reshuffle Data
# input: Response Variables
# output: a Vector
# -------------------
reshuffle_data <- function(dataset){
  shuffle_r <- sample(dataset$response)
  dataset$shuffle <- shuffle_r
  split_df <- aggregate(shuffle_r ~ group_name, dataset, mean)
  split_list <- as.list(split_df)
  return (split_list)
  
}

group1 <- runif(100)
group2 <- runif(100)
group3 <- runif(100)
  
simulate_dataset <- data.frame(group_name = rep(c("group1", "group2", "group3"), each = 100),
                               response = c(group1, group2, group3))

reshuffle_data(simulate_dataset)


```


```{r}
##############################
# FUNCTION: Repeat Reshuffle Data n Times
# input: Response Variables
# output: a Vector
# -------------------

repeat_reshuffle <- function(dataset, repeats) {
  mean_matrix <- data.frame(matrix(nrow = repeats,ncol=4))
  colnames(mean_matrix) <- c("replicate", "group 1", "group 2", "group 3")
  for (i in 1:repeats) {
    reshuffle <- reshuffle_data(dataset)
    mean_matrix[i,1:4] <- c(i,reshuffle$shuffle_r)
    
  }
  return(mean_matrix)
}

num = 100
repeat_reshuffle(simulate_dataset, num)

    
```

```{r,}
#Use qplot() to create a histogram of the means for each reshuffled group. Or, if you want a challenge, use ggplot() to overlay all 3 histograms in the same figure. How do the distributions of reshuffled means compare to the original means?

library(ggplot2)

num = 100
df_new <- repeat_reshuffle(simulate_dataset, num)

g1 <- ggplot(df_new) + aes(x=group1) + geom_histogram(fill="blue",color="navy")

g2 <- ggplot(df_new) + aes(x=group2) + geom_histogram(fill="red",color="purple")

g3 <- ggplot(df_new) + aes(x=group3) + geom_histogram(fill="orange",color="brown")

g1 + g2 + g3 + plot_layout(ncol=1)

```

